<?php

namespace Concrete\Console;

use Concrete\Console\Bootstrap\Booter;
use Concrete\Console\Command\InstallationAwareCommandInterface;
use Concrete\Console\Installation\Factory;
use Concrete\Console\Installation\Validator;
use Symfony\Component\Console\Application as SymfonyApplication;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class Application extends SymfonyApplication
{

    public function __construct()
    {
        parent::__construct('Concrete Console', '0.8');
    }

    public function doRunCommand(Command $command, InputInterface $input, OutputInterface $output)
    {
        if ($command instanceof InstallationAwareCommandInterface) {
            $command->mergeApplicationDefinition();
            $input->bind($command->getDefinition());
            $path = $command->getInstallation($input) ?? null;

            $installationFactory = new Factory();
            if ($path) {
                // Turn the path into something real in case it's relative
                $path = $installationFactory->normalizePath($path);
                $installation = $installationFactory->createFromPath($path);
            } else {
                $installation = $installationFactory->detectInstallation();
            }

            $validator = new Validator();
            if ($validator->isValid($installation)) {
                $booter = new Booter();
                $booter->boot($installation);
            }
        }
        return parent::doRunCommand($command, $input, $output); // TODO: Change the autogenerated stub
    }

}